### ISSUE TITLE
Generalize outputs for both methods

### ISSUE THREAD

**Issue by RoadJDK** [mahogany-dev/M411-Datenstrukturen-Algorithmen#2]
https://github.com/mahogany-dev/M411-Datenstrukturen-Algorithmen/blob/40486146232906adcb00273ed03fd15e3945f65e/datenstrukturen/src/main/java/ch/gibb/algorithmen/ab411_02_collatz/Collatz.java#L72

**Comment by jstnceronio** [comment]
🤓
